INSERT INTO aTEST VALUES (10);
INSERT INTO aTEST VALUES (20);
INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (20);
INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



INSERT INTO aTEST VALUES (30);
INSERT INTO aTEST VALUES (999);



